{{- if .Values.localDev }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-projections-hasura
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: example-projections-hasura
  dataFrom:
  - extract:
      key: /example-hasura
{{- end }}
