{{- if .Values.local }}
{{- else }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: {{ .Values.knative.minScale | quote }}
        autoscaling.knative.dev/maxScale: {{ .Values.knative.maxScale | quote }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        env:
        - name: HASURA_URL
          value: http://example-hasura.{{ .Release.Namespace }}.svc.cluster.local
        - name: HASURA_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: example-projections-hasura
              key: adminSecret
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
