apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: todo.reopened
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  broker: todo-events
  filter:
    attributes:
      type: todo.reopened
  subscriber:
{{- if .Values.knative.eventing.local }}
    uri: {{ .Values.knative.eventing.subscriber }}/cloudevent/todo.reopened
{{- else }}
    ref:
{{- if .Values.knativeDeploy }}
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: {{ .Values.service.name }}
{{- else }}
      apiVersion: v1
      kind: Service
      name: {{ .Values.service.name }}
{{- end }}
    uri: /cloudevent/todo.reopened
{{- end }}