apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: todo.initialized
spec:
  broker: todo-events
  filter:
    attributes:
      type: todo.initialized
  subscriber:
    ref:
{{- if .Values.knativeDeploy }}
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: {{ .Values.service.name }}
{{- else }}
      apiVersion: v1
      kind: Service
      name: {{ .Values.service.name }}
{{- end }}
    uri: /cloudevent/todo.initialized